### ISSUE TITLE
allow setting effect to none

### ISSUE THREAD

**Issue by davidbepo** [klangman/CinnamonBurnMyWindows#1]
just started using this today, very cool, but id like the effect to only apply on closing a window
IMO the easiest way to implement this is to allow selecting none in the list of effects

**Comment by klangman** [comment]
I already have that feature in my local code base along with a partial implementation of a feature allowing users to specify which effects are applied to a specific applications (overriding the general open/close effect settings for specific applications).  I hope to have that code fully implemented in my github in 2-4 days, then a few more days of testing before I submit it to cinnamon-spices.

I'll post again here when the code drops in this repo and again when it's in cinnamon-spices so you can get it.

**Comment by davidbepo** [comment]
cool, thanks for the info
also sorry for this offtopic request, but ive seen you been doing a bunch of cool extensions recently and i was wondering if you could do a rounded windows one like eg https://github.com/yilozt/rounded-window-corners, pretty simple thing but its the only thing missing for my cinnamon UX to be period better than my old gnome one
whether you do it or not, thank you either way for the cool extensions

**Comment by klangman** [comment]
> cool, thanks for the info also sorry for this offtopic request, but ive seen you been doing a bunch of cool extensions recently and i was wondering if you could do a rounded windows one like eg https://github.com/yilozt/rounded-window-corners, pretty simple thing but its the only thing missing for my cinnamon UX to be period better than my old gnome one whether you do it or not, thank you either way for the cool extensions

That extension is written in Typescript, which is not a problem for Cinnamon, but I have never used Typescript before. I'll take a look at porting this once I have a few other tasks done that I am working on now, but given that my experience with Typescript is zero, I am not sure how it'll go. I see it's using GLSLEffect so if I am successful then it would only work in Cinnamon6.2+/Mint22+.

**Comment by davidbepo** [comment]
there are a bunch more with similar names and function, i linked that one in particular because its the one i was using before i switched
thanks for looking into it

**Comment by klangman** [comment]
I just pushed the changes for a "none" option and the "Application Specific Effects" options in the extension configuration to this github reop. I'll do some testing and push the same changes to cinnamon-spices in a few days assuming I don't find any issues.

If you switch to my github version you can try out the new features, or just wait it out and get the cinnamon-spaces update after I push the changes there in a few days.

**Comment by davidbepo** [comment]
tested and working

**Comment by klangman** [comment]
OK.. The changes have been added to the cinnamon-spices version as well now. I think we can close this now?

**Comment by davidbepo** [comment]
> OK.. The changes have been added to the cinnamon-spices version as well now. I think we can close this now?

yep, closing

**Comment by klangman** [comment]
You asked for rounded corners a while back.. Will I did finally give it a go.  Hit some issues which I am not sure how to fix, but it does work in most cases. If I can fix the issues then it might show up on github one day.

(note the rounded bottom corners of the window in this pic)

<img width="896" height="690" alt="Image" src="https://github.com/user-attachments/assets/6d59ac59-bf75-47a4-96e0-c45c7fd0510a" />
